const navGuideCanvas = document.getElementById('navGuideCanvas').getContext('2d'); 
const editGuideCanvas = document.getElementById('editGuideCanvas').getContext('2d'); 

navGuideCanvas.strokeStyle = "green";
navGuideCanvas.font = "20px sans-serif";
navGuideCanvas.fillText("Move/Navigate Keys:", 5, 25);
navGuideCanvas.font = "18.5px sans-serif";
navGuideCanvas.fillText("W -> Up", 5, 60);
navGuideCanvas.fillText("A -> Left    D -> Right", 5, 100);
navGuideCanvas.fillText("S -> Down", 5, 140);
navGuideCanvas.fillText("          -- -- -- -- -- --", 5, 165);
navGuideCanvas.fillText("ESC -> Return/Leave", 5, 180);

editGuideCanvas.strokeStyle = "green";
editGuideCanvas.font = "20px sans-serif";
editGuideCanvas.fillText("Level Editor Keys:", 5, 25);
editGuideCanvas.font = "17px sans-serif";
editGuideCanvas.fillText("G -> Insert by Grid", 5, 60);
editGuideCanvas.fillText("      or Free Form Switch", 5, 80);
editGuideCanvas.fillText("B -> Change Background", 5, 105);
editGuideCanvas.fillText("DEL -> Delete an insert", 5, 135);
editGuideCanvas.fillText("          -- -- -- -- -- --", 5, 155);
editGuideCanvas.font = "17px sans-serif";
editGuideCanvas.fillText("Use mouse to pickup or", 5, 175);
editGuideCanvas.fillText("drop an asset.", 5, 195);
editGuideCanvas.font = "23px sans-serif";
editGuideCanvas.fillText("+ ", 120, 195);
editGuideCanvas.font = "17px sans-serif";
editGuideCanvas.fillText("or", 140, 195);
editGuideCanvas.font = "28px sans-serif";
editGuideCanvas.fillText("-", 162, 195);
editGuideCanvas.font = "17px sans-serif";
editGuideCanvas.fillText("to", 180, 195);
editGuideCanvas.fillText("to change within the ", 5, 215);
editGuideCanvas.fillText("selected asset type", 5, 235);
editGuideCanvas.fillText("T -> Tile insert", 5, 260);
editGuideCanvas.fillText("N -> NPC insert", 5, 285);
editGuideCanvas.fillText("Y -> Decoration insert", 5, 310);
editGuideCanvas.fillText("I  -> Item insert", 5, 335);
editGuideCanvas.fillText("          -- -- -- -- -- --", 5, 355);
editGuideCanvas.font = "18px sans-serif";
editGuideCanvas.fillText("cntrl+enter-> Save&Exit", 5, 370);
