#!/usr/bin/env bash

set -e
echo -e "\033[44m    Running Flow-type removal: ./src/rendering -> ./lib/rendering    \033[m \n"
flow-remove-types ecs/ -d lib/ecs/
echo -e "\n\033[44m    Running Flow-type removal: ./src/rendering -> ./lib/rendering    \033[m \n"
flow-remove-types rendering/ -d lib/rendering/
echo -e "\n\033[45m    Copying ./server/ -> ./lib/server/    \033[m \n"
cp -rf server/ lib/
echo "./server sucessfully coppied to ./lib/server/ !"
echo -e "\n\033[42m    Minimizing ./lib/ecs/    \033[m\n"
uglifyjs-folder lib/ecs/ -x .js -eyo lib/ecs/
echo -e "\n\033[42m    Minimizing ./lib/rendering/    \033[m\n"
uglifyjs-folder lib/rendering/ -x .js -eyo lib/rendering/
echo -e "\n\033[42m    Minimizing ./lib/server/    \033[m\n"
uglifyjs-folder lib/server/ -x .js -eyo lib/server/
echo -e "\n\033[43m    Build Sucessful!    \033[m\n"